import numpy as np 
import pyautogui as auto 
import keyboard 
import os 
from pynput.mouse import Button, Controller 
def main(): 
    def endProgram(): 
        keyboard.unhook_all_hotkeys() 
        print('Ending program in between') 
        os._exit(0) 
    keyboard.add_hotkey('Esc+q', endProgram,suppress=True) 
    mouse = Controller() 
    auto.moveTo( x=1812.671875, y=0.0,duration=1.0) 
    auto.sleep(1.0) 
    auto.mouseDown(button='left', x=1812.671875, y=0.0, duration = 2) 
    auto.moveTo( x=1812.671875, y=0.0,duration=1.1878919601440432) 
    auto.mouseUp(button='left', x=1812.671875, y=0.0, duration = 0.1878919601440432) 
    keyboard.press("c") 
    auto.sleep(1.0) 
    keyboard.press("h") 
    auto.sleep(1.0) 
    keyboard.release("c") 
    auto.sleep(1.0) 
    keyboard.release("h") 
    auto.sleep(1.0) 
    keyboard.press("r") 
    auto.sleep(1.0) 
    keyboard.press("o") 
    auto.sleep(1.0) 
    keyboard.release("r") 
    auto.sleep(1.0) 
    keyboard.release("o") 
    auto.sleep(1.0) 
    keyboard.press("m") 
    auto.sleep(1.0) 
    keyboard.release("m") 
    auto.sleep(1.0) 
    keyboard.press("e") 
    auto.sleep(1.0) 
    keyboard.release("e") 
    auto.sleep(1.0) 
    keyboard.press("enter") 
    auto.sleep(1.0) 
    keyboard.release("enter") 
    auto.sleep(1.0) 
    keyboard.press("command") 
    auto.sleep(1.0) 
    keyboard.press("n") 
    auto.sleep(1.0) 
    keyboard.release("n") 
    auto.sleep(1.0) 
    keyboard.release("command") 
    auto.sleep(1.0) 
